var places = {
  1: {place: 'Aba, Nigeria', city: 'Aba'},
  2: {place: 'Abeokuta, Nigeria', city: 'Abeokuta'},
  3: {place: 'Abidjan, Ivory Coast', city: 'Abidjan'},
  4: {place: 'Abu Dhabi, United Arab Emirates', city: 'Abu Dhabi'},
  5: {place: 'Acapulco, Mexico', city: 'Acapulco'},
  6: {place: 'Accra, Ghana', city: 'Accra'},
  7: {place: 'Adana, Turkey', city: 'Adana'},
  8: {place: 'ad-Dammam, Saudi Arabia', city: 'ad-Dammam'},
  9: {place: 'Addis Abeba, Ethiopia', city: 'Addis Abeba'},
  10: {place: 'Adelaide, Australia', city: 'Adelaide'},
  11: {place: 'Aden, Yemen', city: 'Aden'},
  12: {place: 'Agadir, Morocco', city: 'Agadir'},
  13: {place: 'Agra, India', city: 'Agra'},
  14: {place: 'Aguascalientes, Mexico', city: 'Aguascalientes'},
  15: {place: 'Ahmadabad, India', city: 'Ahmadabad'},
  16: {place: 'Ahvaz, Iran', city: 'Ahvaz'},
  17: {place: 'Ajmer, India', city: 'Ajmer'},
  18: {place: 'al-Basrah, Iraq', city: 'al-Basrah'},
  19: {place: 'Aleppo, Syria', city: 'Aleppo'},
  20: {place: 'Alexandria, Egypt', city: 'Alexandria'},
  21: {place: 'Algiers, Algeria', city: 'Algiers'},
  22: {place: 'al-Khartoum Bahri, Sudan', city: 'al-Khartoum Bahri'},
  23: {place: 'al-Hudaydah, Yemen', city: 'al-Hudaydah'},
  24: {place: 'Aligarh, India', city: 'Aligarh'},
  25: {place: 'Allahabad, India', city: 'Allahabad'},
  26: {place: 'al-Madinah, Saudi Arabia', city: 'al-Madinah'},
  27: {place: 'Almaty, Kazakhstan', city: 'Almaty'},
  28: {place: 'al-Mawsil, Iraq', city: 'al-Mawsil'},
  29: {place: 'Amman, Jordan', city: 'Amman'},
  30: {place: 'Ampang Jaya, Malaysia', city: 'Ampang Jaya'},
  31: {place: 'Amravati, India', city: 'Amravati'},
  32: {place: 'Amritsar, India', city: 'Amritsar'},
  33: {place: 'Amsterdam, Netherlands', city: 'Amsterdam'},
  34: {place: 'Ankara, Turkey', city: 'Ankara'},
  35: {place: 'Ansan, Korea (South)', city: 'Ansan'},
  36: {place: 'Anshan, China', city: 'Anshan'},
  37: {place: 'Antalya, Turkey', city: 'Antalya'},
  38: {place: 'Antananarivo, Madagascar', city: 'Antananarivo'},
  39: {place: 'Antipolo, Philippines', city: 'Antipolo'},
  40: {place: 'Anyang, China', city: 'Anyang'},
  41: {place: 'Anyang, Korea (South)', city: 'Anyang'},
  42: {place: 'Arak, Iran', city: 'Arak'},
  43: {place: 'Arequipa, Peru', city: 'Arequipa'},
  44: {place: 'Asansol, India', city: 'Asansol'},
  45: {place: 'Asgabat, Turkmenistan', city: 'Asgabat'},
  46: {place: 'Asmara, Eritrea', city: 'Asmara'},
  47: {place: 'as-Sulaymaniyah, Iraq', city: 'as-Sulaymaniyah'},
  48: {place: 'Astrakhan, Russia', city: 'Astrakhan'},
  49: {place: 'Asunción, Paraguay', city: 'Asunción'},
  50: {place: 'Athens, Greece', city: 'Athens'},
  51: {place: 'at-Taif, Saudi Arabia', city: 'at-Taif'},
  52: {place: 'Aurangabad, India', city: 'Aurangabad'},
  53: {place: 'Austin, United States', city: 'Austin'},
  54: {place: 'Baghdad, Iraq', city: 'Baghdad'},
  55: {place: 'Bahawalpur, Pakistan', city: 'Bahawalpur'},
  56: {place: 'Baku, Azerbaijan', city: 'Baku'},
  57: {place: 'Baltimore, United States', city: 'Baltimore'},
  58: {place: 'Bamako, Mali', city: 'Bamako'},
  59: {place: 'Bandar Lampung, Indonesia', city: 'Bandar Lampung'},
  60: {place: 'Bandung, Indonesia', city: 'Bandung'},
  61: {place: 'Bangalore, India', city: 'Bangalore'},
  62: {place: 'Bangkok, Thailand', city: 'Bangkok'},
  63: {place: 'Bangui, Central African Republic', city: 'Bangui'},
  64: {place: 'Banjarmasin, Indonesia', city: 'Banjarmasin'},
  65: {place: 'Baoding, China', city: 'Baoding'},
  66: {place: 'Baotou, China', city: 'Baotou'},
  67: {place: 'Barcelona, Spain', city: 'Barcelona'},
  68: {place: 'Bareli, India', city: 'Bareli'},
  69: {place: 'Barnaul, Russia', city: 'Barnaul'},
  70: {place: 'Barquisimeto, Venezuela', city: 'Barquisimeto'},
  71: {place: 'Barranquilla, Colombia', city: 'Barranquilla'},
  72: {place: 'Bayrut, Lebanon', city: 'Bayrut'},
  73: {place: 'Beira, Mozambique', city: 'Beira'},
  74: {place: 'Bekasi, Indonesia', city: 'Bekasi'},
  75: {place: 'Belém, Brazil', city: 'Belém'},
  76: {place: 'Belgrade, Serbia and Montenegro', city: 'Belgrade'},
  77: {place: 'Belo Horizonte, Brazil', city: 'Belo Horizonte'},
  78: {place: 'Bengbu, China', city: 'Bengbu'},
  79: {place: 'Benghazi, Libya', city: 'Benghazi'},
  80: {place: 'Benin, Nigeria', city: 'Benin'},
  81: {place: 'Benoni, South Africa', city: 'Benoni'},
  82: {place: 'Benxi, China', city: 'Benxi'},
  83: {place: 'Berlin, Germany', city: 'Berlin'},
  84: {place: 'Bhavnagar, India', city: 'Bhavnagar'},
  85: {place: 'Bhilai, India', city: 'Bhilai'},
  86: {place: 'Bhiwandi, India', city: 'Bhiwandi'},
  87: {place: 'Bhopal, India', city: 'Bhopal'},
  88: {place: 'Bhubaneswar, India', city: 'Bhubaneswar'},
  89: {place: 'Bikaner, India', city: 'Bikaner'},
  90: {place: 'Birmingham, United Kingdom', city: 'Birmingham'},
  91: {place: 'Biskek, Kyrgyzstan', city: 'Biskek'},
  92: {place: 'Blantyre, Malawi', city: 'Blantyre'},
  93: {place: 'Bogor, Indonesia', city: 'Bogor'},
  94: {place: 'Bogotá, Colombia', city: 'Bogotá'},
  95: {place: 'Bombay, India', city: 'Bombay'},
  96: {place: 'Boston, United States', city: 'Boston'},
  97: {place: 'Bouaké, Ivory Coast', city: 'Bouaké'},
  98: {place: 'Brasília, Brazil', city: 'Brasília'},
  99: {place: 'Brazzaville, Congo', city: 'Brazzaville'},
  100: {place: 'Bremen, Germany', city: 'Bremen'},
  101: {place: 'Brisbane, Australia', city: 'Brisbane'},
  102: {place: 'Brussels, Belgium', city: 'Brussels'},
  103: {place: 'Bucaramanga, Colombia', city: 'Bucaramanga'},
  104: {place: 'Bucharest, Romania', city: 'Bucharest'},
  105: {place: 'Budapest, Hungary', city: 'Budapest'},
  106: {place: 'Buenos Aires, Argentina', city: 'Buenos Aires'},
  107: {place: 'Bulawayo, Zimbabwe', city: 'Bulawayo'},
  108: {place: 'Bursa, Turkey', city: 'Bursa'},
  109: {place: 'Cairo, Egypt', city: 'Cairo'},
  110: {place: 'Calcutta, India', city: 'Calcutta'},
  111: {place: 'Calgary, Canada', city: 'Calgary'},
  112: {place: 'Cali, Colombia', city: 'Cali'},
  113: {place: 'Campinas, Brazil', city: 'Campinas'},
  114: {place: 'Campo Grande, Brazil', city: 'Campo Grande'},
  115: {place: 'Cancún, Mexico', city: 'Cancún'},
  116: {place: 'Cangzhou, China', city: 'Cangzhou'},
  117: {place: 'Cape Town, South Africa', city: 'Cape Town'},
  118: {place: 'Caracas, Venezuela', city: 'Caracas'},
  119: {place: 'Cartagena, Colombia', city: 'Cartagena'},
  120: {place: 'Casablanca, Morocco', city: 'Casablanca'},
  121: {place: 'Cebu, Philippines', city: 'Cebu'},
  122: {place: 'Chandigarh, India', city: 'Chandigarh'},
  123: {place: 'Changchun, China', city: 'Changchun'},
  124: {place: 'Changde, China', city: 'Changde'},
  125: {place: 'Changsha, China', city: 'Changsha'},
  126: {place: 'Changwon, Korea (South)', city: 'Changwon'},
  127: {place: 'Changzhi, China', city: 'Changzhi'},
  128: {place: 'Changzhou, China', city: 'Changzhou'},
  129: {place: 'Charlotte, United States', city: 'Charlotte'},
  130: {place: 'Chattagam, Bangladesh', city: 'Chattagam'},
  131: {place: 'Chelyabinsk, Russia', city: 'Chelyabinsk'},
  132: {place: 'Chengdu, China', city: 'Chengdu'},
  133: {place: 'Chiba, Japan', city: 'Chiba'},
  134: {place: 'Chicago, United States', city: 'Chicago'},
  135: {place: 'Chiclayo, Peru', city: 'Chiclayo'},
  136: {place: 'Chihuahua, Mexico', city: 'Chihuahua'},
  137: {place: 'Chimalhuacán, Mexico', city: 'Chimalhuacán'},
  138: {place: 'Chisinau, Moldova', city: 'Chisinau'},
  139: {place: 'Chongju, Korea (South)', city: 'Chongju'},
  140: {place: 'Chongqing, China', city: 'Chongqing'},
  141: {place: 'Chonju, Korea (South)', city: 'Chonju'},
  142: {place: 'Ciudad Guayana, Venezuela', city: 'Ciudad Guayana'},
  143: {place: 'Cochabamba, Bolivia', city: 'Cochabamba'},
  144: {place: 'Cologne, Germany', city: 'Cologne'},
  145: {place: 'Colombo, Sri Lanka', city: 'Colombo'},
  146: {place: 'Columbus, United States', city: 'Columbus'},
  147: {place: 'Conakry, Guinea', city: 'Conakry'},
  148: {place: 'Contagem, Brazil', city: 'Contagem'},
  149: {place: 'Copenhagen, Denmark', city: 'Copenhagen'},
  150: {place: 'Córdoba, Argentina', city: 'Córdoba'},
  151: {place: 'Cotonou, Benin', city: 'Cotonou'},
  152: {place: 'Cracow, Poland', city: 'Cracow'},
  153: {place: 'Cúcuta, Colombia', city: 'Cúcuta'},
  154: {place: 'Cuiabá, Brazil', city: 'Cuiabá'},
  155: {place: 'Culiacán, Mexico', city: 'Culiacán'},
  156: {place: 'Curitiba, Brazil', city: 'Curitiba'},
  157: {place: 'Dakar, Senegal', city: 'Dakar'},
  158: {place: 'Dalian, China', city: 'Dalian'},
  159: {place: 'Dallas, United States', city: 'Dallas'},
  160: {place: 'Damascus, Syria', city: 'Damascus'},
  161: {place: 'Dandong, China', city: 'Dandong'},
  162: {place: 'Dar es Salaam, Tanzania', city: 'Dar es Salaam'},
  163: {place: 'Datong, China', city: 'Datong'},
  164: {place: 'Davao, Philippines', city: 'Davao'},
  165: {place: 'Dehra Dun, India', city: 'Dehra Dun'},
  166: {place: 'Delhi, India', city: 'Delhi'},
  167: {place: 'Denver, United States', city: 'Denver'},
  168: {place: 'Depok, Indonesia', city: 'Depok'},
  169: {place: 'Detroit, United States', city: 'Detroit'},
  170: {place: 'Dhaka, Bangladesh', city: 'Dhaka'},
  171: {place: 'Diyarbakir, Turkey', city: 'Diyarbakir'},
  172: {place: 'Dnipropetrovsk, Ukraine', city: 'Dnipropetrovsk'},
  173: {place: 'Donetsk, Ukraine', city: 'Donetsk'},
  174: {place: 'Dortmund, Germany', city: 'Dortmund'},
  175: {place: 'Douala, Cameroon', city: 'Douala'},
  176: {place: 'Dubai, United Arab Emirates', city: 'Dubai'},
  177: {place: 'Dublin, Ireland', city: 'Dublin'},
  178: {place: 'Duisburg, Germany', city: 'Duisburg'},
  179: {place: 'Duque de Caxias, Brazil', city: 'Duque de Caxias'},
  180: {place: 'Durban, South Africa', city: 'Durban'},
  181: {place: 'Durgapur, India', city: 'Durgapur'},
  182: {place: 'Dushanbe, Tajikistan', city: 'Dushanbe'},
  183: {place: 'Düsseldorf, Germany', city: 'Düsseldorf'},
  184: {place: 'Ecatepec, Mexico', city: 'Ecatepec'},
  185: {place: 'Edmonton, Canada', city: 'Edmonton'},
  186: {place: 'El Alto, Bolivia', city: 'El Alto'},
  187: {place: 'El Paso, United States', city: 'El Paso'},
  188: {place: 'Enugu, Nigeria', city: 'Enugu'},
  189: {place: 'Esfahan, Iran', city: 'Esfahan'},
  190: {place: 'Eskisehir, Turkey', city: 'Eskisehir'},
  191: {place: 'Essen, Germany', city: 'Essen'},
  192: {place: 'Faisalabad, Pakistan', city: 'Faisalabad'},
  193: {place: 'Faridabad, India', city: 'Faridabad'},
  194: {place: 'Fez, Morocco', city: 'Fez'},
  195: {place: 'Fortaleza, Brazil', city: 'Fortaleza'},
  196: {place: 'Fort Worth, United States', city: 'Fort Worth'},
  197: {place: 'Foshan, China', city: 'Foshan'},
  198: {place: 'Frankfurt, Germany', city: 'Frankfurt'},
  199: {place: 'Freetown, Sierra Leone', city: 'Freetown'},
  200: {place: 'Fukuoka, Japan', city: 'Fukuoka'},
  201: {place: 'Funabashi, Japan', city: 'Funabashi'},
  202: {place: 'Fushun, China', city: 'Fushun'},
  203: {place: 'Fuxin, China', city: 'Fuxin'},
  204: {place: 'Fuzhou, China', city: 'Fuzhou'},
  205: {place: 'Gaziantep, Turkey', city: 'Gaziantep'},
  206: {place: 'Genoa, Italy', city: 'Genoa'},
  207: {place: 'Ghaziabad, India', city: 'Ghaziabad'},
  208: {place: 'Gizeh, Egypt', city: 'Gizeh'},
  209: {place: 'Glasgow, United Kingdom', city: 'Glasgow'},
  210: {place: 'Goiânia, Brazil', city: 'Goiânia'},
  211: {place: 'Gold Coast, Australia', city: 'Gold Coast'},
  212: {place: 'Gorakhpur, India', city: 'Gorakhpur'},
  213: {place: 'Göteborg, Sweden', city: 'Göteborg'},
  214: {place: 'Guadalajara, Mexico', city: 'Guadalajara'},
  215: {place: 'Guadalupe, Mexico', city: 'Guadalupe'},
  216: {place: 'Guangzhou, China', city: 'Guangzhou'},
  217: {place: 'Guarulhos, Brazil', city: 'Guarulhos'},
  218: {place: 'Guatemala, Guatemala', city: 'Guatemala'},
  219: {place: 'Guayaquil, Ecuador', city: 'Guayaquil'},
  220: {place: 'Guilin, China', city: 'Guilin'},
  221: {place: 'Guiyang, China', city: 'Guiyang'},
  222: {place: 'Gujranwala, Pakistan', city: 'Gujranwala'},
  223: {place: 'Guntur, India', city: 'Guntur'},
  224: {place: 'Guwahati, India', city: 'Guwahati'},
  225: {place: 'Gwalior, India', city: 'Gwalior'},
  226: {place: 'Hachioji, Japan', city: 'Hachioji'},
  227: {place: 'Haikou, China', city: 'Haikou'},
  228: {place: 'Hai Phong, Vietnam', city: 'Hai Phong'},
  229: {place: 'Hamadan, Iran', city: 'Hamadan'},
  230: {place: 'Hamamatsu, Japan', city: 'Hamamatsu'},
  231: {place: 'Hamburg, Germany', city: 'Hamburg'},
  232: {place: 'Hamhung, Korea (North)', city: 'Hamhung'},
  233: {place: 'Hamilton, Canada', city: 'Hamilton'},
  234: {place: 'Handan, China', city: 'Handan'},
  235: {place: 'Hangzhou, China', city: 'Hangzhou'},
  236: {place: 'Ha Noi, Vietnam', city: 'Ha Noi'},
  237: {place: 'Hanover, Germany', city: 'Hanover'},
  238: {place: 'Haora, India', city: 'Haora'},
  239: {place: 'Harare, Zimbabwe', city: 'Harare'},
  240: {place: 'Harbin, China', city: 'Harbin'},
  241: {place: 'Hargeysa, Somalia', city: 'Hargeysa'},
  242: {place: 'Havanna, Cuba', city: 'Havanna'},
  243: {place: 'Hefei, China', city: 'Hefei'},
  244: {place: 'Hegang, China', city: 'Hegang'},
  245: {place: 'Helsinki, Finland', city: 'Helsinki'},
  246: {place: 'Hengyang, China', city: 'Hengyang'},
  247: {place: 'Hermosillo, Mexico', city: 'Hermosillo'},
  248: {place: 'Higashiosaka, Japan', city: 'Higashiosaka'},
  249: {place: 'Homs, Syria', city: 'Homs'},
  250: {place: 'Hiroshima, Japan', city: 'Hiroshima'},
  251: {place: 'Ho Chi Minh City, Vietnam', city: 'Ho Chi Minh City'},
  252: {place: 'Hohhot, China', city: 'Hohhot'},
  253: {place: 'Houston, United States', city: 'Houston'},
  254: {place: 'Huaibei, China', city: 'Huaibei'},
  255: {place: 'Huainan, China', city: 'Huainan'},
  256: {place: 'Huaiyin, China', city: 'Huaiyin'},
  257: {place: 'Huangshi, China', city: 'Huangshi'},
  258: {place: 'Hubli, India', city: 'Hubli'},
  259: {place: 'Hyderabad, India', city: 'Hyderabad'},
  260: {place: 'Hyderabad, Pakistan', city: 'Hyderabad'},
  261: {place: 'Ibadan, Nigeria', city: 'Ibadan'},
  262: {place: 'Ilorin, Nigeria', city: 'Ilorin'},
  263: {place: 'Inchon, Korea (South)', city: 'Inchon'},
  264: {place: 'Indianapolis, United States', city: 'Indianapolis'},
  265: {place: 'Indore, India', city: 'Indore'},
  266: {place: 'Ipoh, Malaysia', city: 'Ipoh'},
  267: {place: 'Irbil, Iraq', city: 'Irbil'},
  268: {place: 'Irkutsk, Russia', city: 'Irkutsk'},
  269: {place: 'Islamabad, Pakistan', city: 'Islamabad'},
  270: {place: 'Istanbul, Turkey', city: 'Istanbul'},
  271: {place: 'Izhevsk, Russia', city: 'Izhevsk'},
  272: {place: 'Izmir, Turkey', city: 'Izmir'},
  273: {place: 'Jabalpur, India', city: 'Jabalpur'},
  274: {place: 'Jaboatão, Brazil', city: 'Jaboatão'},
  275: {place: 'Jacksonville, United States', city: 'Jacksonville'},
  276: {place: 'Jaipur, India', city: 'Jaipur'},
  277: {place: 'Jakarta, Indonesia', city: 'Jakarta'},
  278: {place: 'Jalandhar, India', city: 'Jalandhar'},
  279: {place: 'Jamnagar, India', city: 'Jamnagar'},
  280: {place: 'Jamshedpur, India', city: 'Jamshedpur'},
  281: {place: 'Jerusalem, Israel', city: 'Jerusalem'},
  282: {place: 'Jiamusi, China', city: 'Jiamusi'},
  283: {place: 'Jiangmen, China', city: 'Jiangmen'},
  284: {place: 'Jiaozuo, China', city: 'Jiaozuo'},
  285: {place: 'Jibuti, Djibouti', city: 'Jibuti'},
  286: {place: 'Jiddah, Saudi Arabia', city: 'Jiddah'},
  287: {place: 'Jilin, China', city: 'Jilin'},
  288: {place: 'Jinan, China', city: 'Jinan'},
  289: {place: 'Jinzhou, China', city: 'Jinzhou'},
  290: {place: 'Jiulong, China', city: 'Jiulong'},
  291: {place: 'João Pessoa, Brazil', city: 'João Pessoa'},
  292: {place: 'Jodhpur, India', city: 'Jodhpur'},
  293: {place: 'Johannesburg, South Africa', city: 'Johannesburg'},
  294: {place: 'Johor Bahru, Malaysia', city: 'Johor Bahru'},
  295: {place: 'Jos, Nigeria', city: 'Jos'},
  296: {place: 'Juárez, Mexico', city: 'Juárez'},
  297: {place: 'Kabul, Afghanistan', city: 'Kabul'},
  298: {place: 'Kaduna, Nigeria', city: 'Kaduna'},
  299: {place: 'Kagoshima, Japan', city: 'Kagoshima'},
  300: {place: 'Kaifeng, China', city: 'Kaifeng'},
  301: {place: 'Kalyan, India', city: 'Kalyan'},
  302: {place: 'Kampala, Uganda', city: 'Kampala'},
  303: {place: 'Kano, Nigeria', city: 'Kano'},
  304: {place: 'Kanpur, India', city: 'Kanpur'},
  305: {place: 'Kaohsiung, Taiwan', city: 'Kaohsiung'},
  306: {place: 'Karachi, Pakistan', city: 'Karachi'},
  307: {place: 'Karaj, Iran', city: 'Karaj'},
  308: {place: 'Kataka, India', city: 'Kataka'},
  309: {place: 'Kathmandu, Nepal', city: 'Kathmandu'},
  310: {place: 'Kawasaki, Japan', city: 'Kawasaki'},
  311: {place: 'Kayseri, Turkey', city: 'Kayseri'},
  312: {place: 'Kazan, Russia', city: 'Kazan'},
  313: {place: 'Kerman, Iran', city: 'Kerman'},
  314: {place: 'Kermanshah, Iran', city: 'Kermanshah'},
  315: {place: 'Khabarovsk, Russia', city: 'Khabarovsk'},
  316: {place: 'Kharkiv, Ukraine', city: 'Kharkiv'},
  317: {place: 'Khartoum, Sudan', city: 'Khartoum'},
  318: {place: 'Khulna, Bangladesh', city: 'Khulna'},
  319: {place: 'Kiev, Ukraine', city: 'Kiev'},
  320: {place: 'Kigali, Rwanda', city: 'Kigali'},
  321: {place: 'Kingston, Jamaica', city: 'Kingston'},
  322: {place: 'Kinshasa, Congo (Dem. Rep.)', city: 'Kinshasa'},
  323: {place: 'Kirkuk, Iraq', city: 'Kirkuk'},
  324: {place: 'Kisangani, Congo (Dem. Rep.)', city: 'Kisangani'},
  325: {place: 'Kitakyushu, Japan', city: 'Kitakyushu'},
  326: {place: 'Klang, Malaysia', city: 'Klang'},
  327: {place: 'Kobe, Japan', city: 'Kobe'},
  328: {place: 'Kochi, India', city: 'Kochi'},
  329: {place: 'Kolhapur, India', city: 'Kolhapur'},
  330: {place: 'Kolwezi, Congo (Dem. Rep.)', city: 'Kolwezi'},
  331: {place: 'Konya, Turkey', city: 'Konya'},
  332: {place: 'Kota, India', city: 'Kota'},
  333: {place: 'Koyampattur, India', city: 'Koyampattur'},
  334: {place: 'Koyang, Korea (South)', city: 'Koyang'},
  335: {place: 'Krasnodar, Russia', city: 'Krasnodar'},
  336: {place: 'Krasnoyarsk, Russia', city: 'Krasnoyarsk'},
  337: {place: 'Kryvyy Rih, Ukraine', city: 'Kryvyy Rih'},
  338: {place: 'Kuala Lumpur, Malaysia', city: 'Kuala Lumpur'},
  339: {place: 'Kuching, Malaysia', city: 'Kuching'},
  340: {place: 'Kumamoto, Japan', city: 'Kumamoto'},
  341: {place: 'Kumasi, Ghana', city: 'Kumasi'},
  342: {place: 'Kunming, China', city: 'Kunming'},
  343: {place: 'Kwangju, Korea (South)', city: 'Kwangju'},
  344: {place: 'Kyoto, Japan', city: 'Kyoto'},
  345: {place: 'Lagos, Nigeria', city: 'Lagos'},
  346: {place: 'Lahore, Pakistan', city: 'Lahore'},
  347: {place: 'Lakhnau, India', city: 'Lakhnau'},
  348: {place: 'Langfang, China', city: 'Langfang'},
  349: {place: 'Lanzhou, China', city: 'Lanzhou'},
  350: {place: 'La Paz, Bolivia', city: 'La Paz'},
  351: {place: 'La Plata, Argentina', city: 'La Plata'},
  352: {place: 'Las Vegas, United States', city: 'Las Vegas'},
  353: {place: 'Leipzig, Germany', city: 'Leipzig'},
  354: {place: 'León, Mexico', city: 'León'},
  355: {place: 'Liaoyang, China', city: 'Liaoyang'},
  356: {place: 'Libreville, Gabon', city: 'Libreville'},
  357: {place: 'Lilongwe, Malawi', city: 'Lilongwe'},
  358: {place: 'Lima, Peru', city: 'Lima'},
  359: {place: 'Lipetsk, Russia', city: 'Lipetsk'},
  360: {place: 'Lisbon, Portugal', city: 'Lisbon'},
  361: {place: 'Liuzhou, China', city: 'Liuzhou'},
  362: {place: 'Lódz, Poland', city: 'Lódz'},
  363: {place: 'Lomé, Togo', city: 'Lomé'},
  364: {place: 'London, United Kingdom', city: 'London'},
  365: {place: 'López Mateos, Mexico', city: 'López Mateos'},
  366: {place: 'Los Angeles, United States', city: 'Los Angeles'},
  367: {place: 'Luancheng, China', city: 'Luancheng'},
  368: {place: 'Luanda, Angola', city: 'Luanda'},
  369: {place: 'Lubumbashi, Congo (Dem. Rep.)', city: 'Lubumbashi'},
  370: {place: 'Ludhiana, India', city: 'Ludhiana'},
  371: {place: 'Luoyang, China', city: 'Luoyang'},
  372: {place: 'Lusaka, Zambia', city: 'Lusaka'},
  373: {place: 'Lviv, Ukraine', city: 'Lviv'},
  374: {place: 'Maanshan, China', city: 'Maanshan'},
  375: {place: 'Maceió, Brazil', city: 'Maceió'},
  376: {place: 'Madras, India', city: 'Madras'},
  377: {place: 'Madrid, Spain', city: 'Madrid'},
  378: {place: 'Madurai, India', city: 'Madurai'},
  379: {place: 'Maiduguri, Nigeria', city: 'Maiduguri'},
  380: {place: 'Maisuru, India', city: 'Maisuru'},
  381: {place: 'Makasar, Indonesia', city: 'Makasar'},
  382: {place: 'Makhachkala, Russia', city: 'Makhachkala'},
  383: {place: 'Málaga, Spain', city: 'Málaga'},
  384: {place: 'Malang, Indonesia', city: 'Malang'},
  385: {place: 'Managua, Nicaragua', city: 'Managua'},
  386: {place: 'Manaus, Brazil', city: 'Manaus'},
  387: {place: 'Mandalay, Myanmar', city: 'Mandalay'},
  388: {place: 'Manila, Philippines', city: 'Manila'},
  389: {place: 'Maoming, China', city: 'Maoming'},
  390: {place: 'Maputo, Mozambique', city: 'Maputo'},
  391: {place: 'Maracaibo, Venezuela', city: 'Maracaibo'},
  392: {place: 'Mar del Plata, Argentina', city: 'Mar del Plata'},
  393: {place: 'Marrakesh, Morocco', city: 'Marrakesh'},
  394: {place: 'Marseille, France', city: 'Marseille'},
  395: {place: 'Mashhad, Iran', city: 'Mashhad'},
  396: {place: 'Matola, Mozambique', city: 'Matola'},
  397: {place: 'Mbuji-Mayi, Congo (Dem. Rep.)', city: 'Mbuji-Mayi'},
  398: {place: 'Mecca, Saudi Arabia', city: 'Mecca'},
  399: {place: 'Medan, Indonesia', city: 'Medan'},
  400: {place: 'Medellín, Colombia', city: 'Medellín'},
  401: {place: 'Meknes, Morocco', city: 'Meknes'},
  402: {place: 'Melbourne, Australia', city: 'Melbourne'},
  403: {place: 'Memphis, United States', city: 'Memphis'},
  404: {place: 'Mendoza, Argentina', city: 'Mendoza'},
  405: {place: 'Mérida, Mexico', city: 'Mérida'},
  406: {place: 'Mersin, Turkey', city: 'Mersin'},
  407: {place: 'Mexicali, Mexico', city: 'Mexicali'},
  408: {place: 'Mexico City, Mexico', city: 'Mexico City'},
  409: {place: 'Milan, Italy', city: 'Milan'},
  410: {place: 'Milwaukee, United States', city: 'Milwaukee'},
  411: {place: 'Minsk, Belarus', city: 'Minsk'},
  412: {place: 'Mira Bhayandar, India', city: 'Mira Bhayandar'},
  413: {place: 'Mirat, India', city: 'Mirat'},
  414: {place: 'Mixco, Guatemala', city: 'Mixco'},
  415: {place: 'Mogadishu, Somalia', city: 'Mogadishu'},
  416: {place: 'Mombasa, Kenya', city: 'Mombasa'},
  417: {place: 'Monrovia, Liberia', city: 'Monrovia'},
  418: {place: 'Monterrey, Mexico', city: 'Monterrey'},
  419: {place: 'Montevideo, Uruguay', city: 'Montevideo'},
  420: {place: 'Montreal, Canada', city: 'Montreal'},
  421: {place: 'Moradabad, India', city: 'Moradabad'},
  422: {place: 'Morelia, Mexico', city: 'Morelia'},
  423: {place: 'Moscow, Russia', city: 'Moscow'},
  424: {place: 'Mudanjiang, China', city: 'Mudanjiang'},
  425: {place: 'Multan, Pakistan', city: 'Multan'},
  426: {place: 'Munich, Germany', city: 'Munich'},
  427: {place: 'Mykolayiv, Ukraine', city: 'Mykolayiv'},
  428: {place: 'Naberezhnyye Chelny, Russia', city: 'Naberezhnyye Chelny'},
  429: {place: 'Nagoya, Japan', city: 'Nagoya'},
  430: {place: 'Nagpur, India', city: 'Nagpur'},
  431: {place: 'Nairobi, Kenya', city: 'Nairobi'},
  432: {place: 'Nanchang, China', city: 'Nanchang'},
  433: {place: 'Nanjing, China', city: 'Nanjing'},
  434: {place: 'Nanning, China', city: 'Nanning'},
  435: {place: 'Nantong, China', city: 'Nantong'},
  436: {place: 'Naples, Italy', city: 'Naples'},
  437: {place: 'Nashik, India', city: 'Nashik'},
  438: {place: 'Nashville, United States', city: 'Nashville'},
  439: {place: 'Natal, Brazil', city: 'Natal'},
  440: {place: 'Naucalpan, Mexico', city: 'Naucalpan'},
  441: {place: 'Navi Mumbai, India', city: 'Navi Mumbai'},
  442: {place: 'N’Djaména, Chad', city: 'N’Djaména'},
  443: {place: 'Neijiang, China', city: 'Neijiang'},
  444: {place: 'Newcastle, Australia', city: 'Newcastle'},
  445: {place: 'New York, United States', city: 'New York'},
  446: {place: 'Nezahualcóyotl, Mexico', city: 'Nezahualcóyotl'},
  447: {place: 'Niamey, Niger', city: 'Niamey'},
  448: {place: 'Niigata, Japan', city: 'Niigata'},
  449: {place: 'Ningbo, China', city: 'Ningbo'},
  450: {place: 'Niyala, Sudan', city: 'Niyala'},
  451: {place: 'Nizhniy Novgorod, Russia', city: 'Nizhniy Novgorod'},
  452: {place: 'Nouakchott, Mauritania', city: 'Nouakchott'},
  453: {place: 'Nova Iguaçu, Brazil', city: 'Nova Iguaçu'},
  454: {place: 'Novokuznetsk, Russia', city: 'Novokuznetsk'},
  455: {place: 'Novosibirsk, Russia', city: 'Novosibirsk'},
  456: {place: 'Odesa, Ukraine', city: 'Odesa'},
  457: {place: 'Ogbomosho, Nigeria', city: 'Ogbomosho'},
  458: {place: 'Okayama, Japan', city: 'Okayama'},
  459: {place: 'Oklahoma City, United States', city: 'Oklahoma City'},
  460: {place: 'Omsk, Russia', city: 'Omsk'},
  461: {place: 'Onitsha, Nigeria', city: 'Onitsha'},
  462: {place: 'Orenburg, Russia', city: 'Orenburg'},
  463: {place: 'Orumiyeh, Iran', city: 'Orumiyeh'},
  464: {place: 'Osaka, Japan', city: 'Osaka'},
  465: {place: 'Osasco, Brazil', city: 'Osasco'},
  466: {place: 'Oshogbo, Nigeria', city: 'Oshogbo'},
  467: {place: 'Oslo, Norway', city: 'Oslo'},
  468: {place: 'Ottawa, Canada', city: 'Ottawa'},
  469: {place: 'Ouagadougou, Burkina Faso', city: 'Ouagadougou'},
  470: {place: 'Oyo, Nigeria', city: 'Oyo'},
  471: {place: 'Padang, Indonesia', city: 'Padang'},
  472: {place: 'Palembang, Indonesia', city: 'Palembang'},
  473: {place: 'Palermo, Italy', city: 'Palermo'},
  474: {place: 'Panjin, China', city: 'Panjin'},
  475: {place: 'Paris, France', city: 'Paris'},
  476: {place: 'Patna, India', city: 'Patna'},
  477: {place: 'Pekan Baru, Indonesia', city: 'Pekan Baru'},
  478: {place: 'Peking, China', city: 'Peking'},
  479: {place: 'Penza, Russia', city: 'Penza'},
  480: {place: 'Perm, Russia', city: 'Perm'},
  481: {place: 'Perth, Australia', city: 'Perth'},
  482: {place: 'Peshawar, Pakistan', city: 'Peshawar'},
  483: {place: 'Petaling Jaya, Malaysia', city: 'Petaling Jaya'},
  484: {place: 'Philadelphia, United States', city: 'Philadelphia'},
  485: {place: 'Phnum Pénh, Cambodia', city: 'Phnum Pénh'},
  486: {place: 'Phoenix, United States', city: 'Phoenix'},
  487: {place: 'Pietermaritzburg, South Africa', city: 'Pietermaritzburg'},
  488: {place: 'Pimpri, India', city: 'Pimpri'},
  489: {place: 'Pingdingshan, China', city: 'Pingdingshan'},
  490: {place: 'Pointe Noire, Congo', city: 'Pointe Noire'},
  491: {place: 'Port-au-Prince, Haiti', city: 'Port-au-Prince'},
  492: {place: 'Port Elizabeth, South Africa', city: 'Port Elizabeth'},
  493: {place: 'Port Harcourt, Nigeria', city: 'Port Harcourt'},
  494: {place: 'Portland, United States', city: 'Portland'},
  495: {place: 'Porto Alegre, Brazil', city: 'Porto Alegre'},
  496: {place: 'Port Said, Egypt', city: 'Port Said'},
  497: {place: 'Poznan, Poland', city: 'Poznan'},
  498: {place: 'Prague, Czech Republic', city: 'Prague'},
  499: {place: 'Pretoria, South Africa', city: 'Pretoria'},
  500: {place: 'Puchon, Korea (South)', city: 'Puchon'},
  501: {place: 'Puebla, Mexico', city: 'Puebla'},
  502: {place: 'Puente Alto, Chile', city: 'Puente Alto'},
  503: {place: 'Pune, India', city: 'Pune'},
  504: {place: 'Pusan, Korea (South)', city: 'Pusan'},
  505: {place: 'Puyang, China', city: 'Puyang'},
  506: {place: 'Pyongyang, Korea (North)', city: 'Pyongyang'},
  507: {place: 'Qingdao, China', city: 'Qingdao'},
  508: {place: 'Qinhuangdao, China', city: 'Qinhuangdao'},
  509: {place: 'Qiqihar, China', city: 'Qiqihar'},
  510: {place: 'Qom, Iran', city: 'Qom'},
  511: {place: 'Quebec, Canada', city: 'Quebec'},
  512: {place: 'Querétaro, Mexico', city: 'Querétaro'},
  513: {place: 'Quetta, Pakistan', city: 'Quetta'},
  514: {place: 'Quito, Ecuador', city: 'Quito'},
  515: {place: 'Rabat, Morocco', city: 'Rabat'},
  516: {place: 'Raipur, India', city: 'Raipur'},
  517: {place: 'Rajkot, India', city: 'Rajkot'},
  518: {place: 'Rajshahi, Bangladesh', city: 'Rajshahi'},
  519: {place: 'Ranchi, India', city: 'Ranchi'},
  520: {place: 'Rangoon, Myanmar', city: 'Rangoon'},
  521: {place: 'Rasht, Iran', city: 'Rasht'},
  522: {place: 'Rawalpindi, Pakistan', city: 'Rawalpindi'},
  523: {place: 'Recife, Brazil', city: 'Recife'},
  524: {place: 'Reynosa, Mexico', city: 'Reynosa'},
  525: {place: 'Ribeirão Preto, Brazil', city: 'Ribeirão Preto'},
  526: {place: 'Riga, Latvia', city: 'Riga'},
  527: {place: 'Rio de Janeiro, Brazil', city: 'Rio de Janeiro'},
  528: {place: 'Riyadh, Saudi Arabia', city: 'Riyadh'},
  529: {place: 'Rome, Italy', city: 'Rome'},
  530: {place: 'Rongcheng, China', city: 'Rongcheng'},
  531: {place: 'Rosario, Argentina', city: 'Rosario'},
  532: {place: 'Rostov-na-Donu, Russia', city: 'Rostov-na-Donu'},
  533: {place: 'Rotterdam, Netherlands', city: 'Rotterdam'},
  534: {place: 'Ryazan, Russia', city: 'Ryazan'},
  535: {place: 'Sagamihara, Japan', city: 'Sagamihara'},
  536: {place: 'Saint Petersburg, Russia', city: 'Saint Petersburg'},
  537: {place: 'Saitama, Japan', city: 'Saitama'},
  538: {place: 'Sakai, Japan', city: 'Sakai'},
  539: {place: 'Salta, Argentina', city: 'Salta'},
  540: {place: 'Saltillo, Mexico', city: 'Saltillo'},
  541: {place: 'Salvador, Brazil', city: 'Salvador'},
  542: {place: 'Samara, Russia', city: 'Samara'},
  543: {place: 'San’a, Yemen', city: 'San’a'},
  544: {place: 'San Antonio, United States', city: 'San Antonio'},
  545: {place: 'San Diego, United States', city: 'San Diego'},
  546: {place: 'San Francisco, United States', city: 'San Francisco'},
  547: {place: 'Sangli-Miraj, India', city: 'Sangli-Miraj'},
  548: {place: 'San Jose, United States', city: 'San Jose'},
  549: {place: 'San Luis Potosí, Mexico', city: 'San Luis Potosí'},
  550: {place: 'San Nicolás de los Garza, Mexico', city: 'San Nicolás de los Garza'},
  551: {place: 'San Pedro Sula, Honduras', city: 'San Pedro Sula'},
  552: {place: 'San Salvador, El Salvador', city: 'San Salvador'},
  553: {place: 'Santa Cruz, Bolivia', city: 'Santa Cruz'},
  554: {place: 'Santiago, Chile', city: 'Santiago'},
  555: {place: 'Santiago, Dominican Republic', city: 'Santiago'},
  556: {place: 'Santiago de Cuba, Cuba', city: 'Santiago de Cuba'},
  557: {place: 'Santo André, Brazil', city: 'Santo André'},
  558: {place: 'Santo Domingo, Dominican Republic', city: 'Santo Domingo'},
  559: {place: 'São Bernardo do Campo, Brazil', city: 'São Bernardo do Campo'},
  560: {place: 'São Gonçalo, Brazil', city: 'São Gonçalo'},
  561: {place: 'São José dos Campos, Brazil', city: 'São José dos Campos'},
  562: {place: 'São Luís, Brazil', city: 'São Luís'},
  563: {place: 'São Paulo, Brazil', city: 'São Paulo'},
  564: {place: 'Sapporo, Japan', city: 'Sapporo'},
  565: {place: 'Sarajevo, Bosnia and Herzegovina', city: 'Sarajevo'},
  566: {place: 'Saratov, Russia', city: 'Saratov'},
  567: {place: 'Sargodha, Pakistan', city: 'Sargodha'},
  568: {place: 'Seattle, United States', city: 'Seattle'},
  569: {place: 'Selam, India', city: 'Selam'},
  570: {place: 'Semarang, Indonesia', city: 'Semarang'},
  571: {place: 'Sendai, Japan', city: 'Sendai'},
  572: {place: 'Sevilla, Spain', city: 'Sevilla'},
  573: {place: 'Shah Alam, Malaysia', city: 'Shah Alam'},
  574: {place: 'Shanghai, China', city: 'Shanghai'},
  575: {place: 'Shantou, China', city: 'Shantou'},
  576: {place: 'Shaoguan, China', city: 'Shaoguan'},
  577: {place: 'Shaoyang, China', city: 'Shaoyang'},
  578: {place: 'Sharjah, United Arab Emirates', city: 'Sharjah'},
  579: {place: 'Shashi, China', city: 'Shashi'},
  580: {place: 'Shatian, China', city: 'Shatian'},
  581: {place: 'Shenyang, China', city: 'Shenyang'},
  582: {place: 'Shenzhen, China', city: 'Shenzhen'},
  583: {place: 'Shihezi, China', city: 'Shihezi'},
  584: {place: 'Shihung, Korea (South)', city: 'Shihung'},
  585: {place: 'Shijiazhuang, China', city: 'Shijiazhuang'},
  586: {place: 'Shiliguri, India', city: 'Shiliguri'},
  587: {place: 'Shiraz, Iran', city: 'Shiraz'},
  588: {place: 'Shizuoka, Japan', city: 'Shizuoka'},
  589: {place: 'Sholapur, India', city: 'Sholapur'},
  590: {place: 'Shubra-El-Khema, Egypt', city: 'Shubra-El-Khema'},
  591: {place: 'Singapore, Singapore', city: 'Singapore'},
  592: {place: 'Siping, China', city: 'Siping'},
  593: {place: 'Sofia, Bulgaria', city: 'Sofia'},
  594: {place: 'Sokoto, Nigeria', city: 'Sokoto'},
  595: {place: 'Songnam, Korea (South)', city: 'Songnam'},
  596: {place: 'Sorocaba, Brazil', city: 'Sorocaba'},
  597: {place: 'Soul, Korea (South)', city: 'Soul'},
  598: {place: 'Soweto, South Africa', city: 'Soweto'},
  599: {place: 'Srinagar, India', city: 'Srinagar'},
  600: {place: 'Stockholm, Sweden', city: 'Stockholm'},
  601: {place: 'Stuttgart, Germany', city: 'Stuttgart'},
  602: {place: 'Subang Jaya, Malaysia', city: 'Subang Jaya'},
  603: {place: 'Surabaya, Indonesia', city: 'Surabaya'},
  604: {place: 'Surakarta, Indonesia', city: 'Surakarta'},
  605: {place: 'Surat, India', city: 'Surat'},
  606: {place: 'Suwon, Korea (South)', city: 'Suwon'},
  607: {place: 'Suzhou, China', city: 'Suzhou'},
  608: {place: 'Sydney, Australia', city: 'Sydney'},
  609: {place: 'Tabriz, Iran', city: 'Tabriz'},
  610: {place: 'Taegu, Korea (South)', city: 'Taegu'},
  611: {place: 'Taejon, Korea (South)', city: 'Taejon'},
  612: {place: 'Taian, China', city: 'Taian'},
  613: {place: 'Taichung, Taiwan', city: 'Taichung'},
  614: {place: 'Tainan, Taiwan', city: 'Tainan'},
  615: {place: 'Taipei, Taiwan', city: 'Taipei'},
  616: {place: 'Taiyuan, China', city: 'Taiyuan'},
  617: {place: 'Taizhou, China', city: 'Taizhou'},
  618: {place: 'Ta’izz, Yemen', city: 'Ta’izz'},
  619: {place: 'Tangerang, Indonesia', city: 'Tangerang'},
  620: {place: 'Tanggu, China', city: 'Tanggu'},
  621: {place: 'Tangier, Morocco', city: 'Tangier'},
  622: {place: 'Tangshan, China', city: 'Tangshan'},
  623: {place: 'Tashkent, Uzbekistan', city: 'Tashkent'},
  624: {place: 'Tbilisi, Georgia', city: 'Tbilisi'},
  625: {place: 'Tegucigalpa, Honduras', city: 'Tegucigalpa'},
  626: {place: 'Tehran, Iran', city: 'Tehran'},
  627: {place: 'Tembisa, South Africa', city: 'Tembisa'},
  628: {place: 'Teresina, Brazil', city: 'Teresina'},
  629: {place: 'Thana, India', city: 'Thana'},
  630: {place: 'Thiruvananthapuram, India', city: 'Thiruvananthapuram'},
  631: {place: 'Tianjin, China', city: 'Tianjin'},
  632: {place: 'Tijuana, Mexico', city: 'Tijuana'},
  633: {place: 'Tiruchchirappalli, India', city: 'Tiruchchirappalli'},
  634: {place: 'Tlalnepantla, Mexico', city: 'Tlalnepantla'},
  635: {place: 'Tlaquepaque, Mexico', city: 'Tlaquepaque'},
  636: {place: 'Tokyo, Japan', city: 'Tokyo'},
  637: {place: 'Toluca, Mexico', city: 'Toluca'},
  638: {place: 'Tolyatti, Russia', city: 'Tolyatti'},
  639: {place: 'Toronto, Canada', city: 'Toronto'},
  640: {place: 'Torreón, Mexico', city: 'Torreón'},
  641: {place: 'Tripoli, Libya', city: 'Tripoli'},
  642: {place: 'Trujillo, Peru', city: 'Trujillo'},
  643: {place: 'Tucson, United States', city: 'Tucson'},
  644: {place: 'Tucumán, Argentina', city: 'Tucumán'},
  645: {place: 'Tunis, Tunisia', city: 'Tunis'},
  646: {place: 'Turin, Italy', city: 'Turin'},
  647: {place: 'Tyumen, Russia', city: 'Tyumen'},
  648: {place: 'Uberlândia, Brazil', city: 'Uberlândia'},
  649: {place: 'Ufa, Russia', city: 'Ufa'},
  650: {place: 'Uijongbu, Korea (South)', city: 'Uijongbu'},
  651: {place: 'Ulaanbaatar, Mongolia', city: 'Ulaanbaatar'},
  652: {place: 'Ulhasnagar, India', city: 'Ulhasnagar'},
  653: {place: 'Ulsan, Korea (South)', city: 'Ulsan'},
  654: {place: 'Ulyanovsk, Russia', city: 'Ulyanovsk'},
  655: {place: 'Umm Durman, Sudan', city: 'Umm Durman'},
  656: {place: 'Urumqi, China', city: 'Urumqi'},
  657: {place: 'Vadodara, India', city: 'Vadodara'},
  658: {place: 'Valencia, Venezuela', city: 'Valencia'},
  659: {place: 'Valencia, Spain', city: 'Valencia'},
  660: {place: 'Vancouver, Canada', city: 'Vancouver'},
  661: {place: 'Varanasi, India', city: 'Varanasi'},
  662: {place: 'Veracruz, Mexico', city: 'Veracruz'},
  663: {place: 'Vienna, Austria', city: 'Vienna'},
  664: {place: 'Vijayawada, India', city: 'Vijayawada'},
  665: {place: 'Vilnius, Lithuania', city: 'Vilnius'},
  666: {place: 'Visakhapatnam, India', city: 'Visakhapatnam'},
  667: {place: 'Vladivostok, Russia', city: 'Vladivostok'},
  668: {place: 'Volgograd, Russia', city: 'Volgograd'},
  669: {place: 'Voronezh, Russia', city: 'Voronezh'},
  670: {place: 'Wahran, Algeria', city: 'Wahran'},
  671: {place: 'Warangal, India', city: 'Warangal'},
  672: {place: 'Warri, Nigeria', city: 'Warri'},
  673: {place: 'Warsaw, Poland', city: 'Warsaw'},
  674: {place: 'Washington DC, United States', city: 'Washington DC'},
  675: {place: 'Wenzhou, China', city: 'Wenzhou'},
  676: {place: 'Winnipeg, Canada', city: 'Winnipeg'},
  677: {place: 'Wroclaw, Poland', city: 'Wroclaw'},
  678: {place: 'Wuhan, China', city: 'Wuhan'},
  679: {place: 'Wuhu, China', city: 'Wuhu'},
  680: {place: 'Wuxi, China', city: 'Wuxi'},
  681: {place: 'Xiamen, China', city: 'Xiamen'},
  682: {place: 'Xian, China', city: 'Xian'},
  683: {place: 'Xianggangdao, China', city: 'Xianggangdao'},
  684: {place: 'Xiangtan, China', city: 'Xiangtan'},
  685: {place: 'Xianyang, China', city: 'Xianyang'},
  686: {place: 'Xingtai, China', city: 'Xingtai'},
  687: {place: 'Xining, China', city: 'Xining'},
  688: {place: 'Xinxiang, China', city: 'Xinxiang'},
  689: {place: 'Xinyang, China', city: 'Xinyang'},
  690: {place: 'Xuzhou, China', city: 'Xuzhou'},
  691: {place: 'Yancheng, China', city: 'Yancheng'},
  692: {place: 'Yangzhou, China', city: 'Yangzhou'},
  693: {place: 'Yantai, China', city: 'Yantai'},
  694: {place: 'Yaoundé, Cameroon', city: 'Yaoundé'},
  695: {place: 'Yaroslavl, Russia', city: 'Yaroslavl'},
  696: {place: 'Yazd, Iran', city: 'Yazd'},
  697: {place: 'Yekaterinburg, Russia', city: 'Yekaterinburg'},
  698: {place: 'Yerevan, Armenia', city: 'Yerevan'},
  699: {place: 'Yingkou, China', city: 'Yingkou'},
  700: {place: 'Yogyakarta, Indonesia', city: 'Yogyakarta'},
  701: {place: 'Yokohama, Japan', city: 'Yokohama'},
  702: {place: 'Yuanlong, China', city: 'Yuanlong'},
  703: {place: 'Yueyang, China', city: 'Yueyang'},
  704: {place: 'Zagreb, Croatia', city: 'Zagreb'},
  705: {place: 'Zahedan, Iran', city: 'Zahedan'},
  706: {place: 'Zapopan, Mexico', city: 'Zapopan'},
  707: {place: 'Zaporizhzhya, Ukraine', city: 'Zaporizhzhya'},
  708: {place: 'Zaragoza, Spain', city: 'Zaragoza'},
  709: {place: 'Zaria, Nigeria', city: 'Zaria'},
  710: {place: 'Zhangdian, China', city: 'Zhangdian'},
  711: {place: 'Zhangjiakou, China', city: 'Zhangjiakou'},
  712: {place: 'Zhangzhou, China', city: 'Zhangzhou'},
  713: {place: 'Zhanjiang, China', city: 'Zhanjiang'},
  714: {place: 'Zhengzhou, China', city: 'Zhengzhou'},
  715: {place: 'Zhenjiang, China', city: 'Zhenjiang'},
  716: {place: 'Zhuhai, China', city: 'Zhuhai'},
  717: {place: 'Zhunmen, China', city: 'Zhunmen'},
  718: {place: 'Zhuzhou, China', city: 'Zhuzhou'},
  719: {place: 'Zigong, China', city: 'Zigong'},
};
  
exports.randomPlace = function() {
  // Use Object.keys to get lenght of places object
  var rand = Math.floor(Math.random()* Object.keys(places).length);
  return places[rand];
};

